env:
    es2021: true
ignorePatterns:
    - "bin"
    - "dist"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
rules:
    eqeqeq: error
    no-var: error
    no-eval: error
    no-return-await: error
    no-loop-func: error
    no-lonely-if: error
    no-irregular-whitespace: error
    no-unmodified-loop-condition: error
    no-unreachable: error
    no-unreachable-loop: error
    no-buffer-constructor: error
    no-negated-condition: error
    no-sequences: error
    require-await: error
    no-console: warn
    camelcase:
        - error
        - properties: never
          ignoreDestructuring: true
          ignoreImports: true
    curly:
        - error
        - multi-or-nest
        - consistent
    quotes:
        - error
        - double
    semi:
        - error
        - never
